spring:
  application:
    name: prometheus-exporter-demo
server:
  port: 9002
#服务停止
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true
  metrics:
    enable:
      jvm: false
      logback: false
      process.files: false
      process.uptime: false
      process.start.time: false
      system.cpu: false
      process.cpu: false
      tomcat: false
      http: false
      system: false
